"""Add is_manufacturer, is_supplier, contact_person to customers

Revision ID: 106283044023
Revises: ec0e4044784f
Create Date: 2026-02-23 10:22:16.624482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '106283044023'
down_revision = 'ec0e4044784f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('manufacturers')
    op.drop_table('suppliers')
    op.drop_table('test')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manufacturer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_supplier', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=100), nullable=True))

    with op.batch_alter_table('product_suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_suppliers_supplier_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['supplier_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('products_manufacturer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['manufacturer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'currencies', ['currency_id'], ['id'])
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_manufacturer_id_fkey'), 'manufacturers', ['manufacturer_id'], ['id'])
        batch_op.drop_column('currency_id')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('product_suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_suppliers_supplier_id_fkey'), 'suppliers', ['supplier_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('contact_person')
        batch_op.drop_column('is_supplier')
        batch_op.drop_column('is_manufacturer')

    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inn', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('kpp', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ogrn', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suppliers_pkey')),
    sa.UniqueConstraint('inn', name=op.f('suppliers_inn_key')),
    sa.UniqueConstraint('name', name=op.f('suppliers_name_key'))
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('manufacturers_pkey')),
    sa.UniqueConstraint('name', name=op.f('manufacturers_name_key'))
    )
    op.drop_table('currencies')
    # ### end Alembic commands ###
