"""Add comment field to StockLog

Revision ID: 571b1205d13f
Revises: 22753a4af67d
Create Date: 2026-02-22 13:49:51.568795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571b1205d13f'
down_revision = '22753a4af67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_logs', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
